### ISSUE TITLE
Module doesn't respect that Scotland is its own country

### ISSUE THREAD

**Issue by DouglasBoubert** [adamjermyn/Britain#1]
I should be able to choose any of the countries within Britain when importing this module, see examples below:

from britain import scottish
from britain import welsh
from britain import irish
from britain import northern_irish

This is a mission critical bug, please fix ASAP.

**Comment by adamjermyn** [comment]
I would happily rectify the situation if you can point me to American-(Scottish/Northern Irish/Welsh)) word lists.

**Comment by DouglasBoubert** [comment]
No, Scottish English is the same as English English but spoken in a friendlier way. Allow the user to freely choose between from britain import scottish and from britain import english, but penalise people who pick the latter by adding a time.sleep(5) in the import.

**Comment by adamjermyn** [comment]
I amn’t sure that that’s precisely true.

I’ll add an option to import any of them but will not penalize the majority of users.

**Comment by DouglasBoubert** [comment]
Ach, at least print a custom message on import depending on which the user chose! A flag perhaps?

**Comment by adamjermyn** [comment]
It now supports importing any of the countries which make up the Union.

**Comment by DouglasBoubert** [comment]
Arguably you are missing a few, [see here](https://en.wikipedia.org/wiki/Terminology_of_the_British_Isles).

**Comment by adamjermyn** [comment]
‘Isle-of-manish’ doesn’t have the same ring to it...

**Comment by DouglasBoubert** [comment]
The accurate term is ['Manx'](https://en.wikipedia.org/wiki/Manx_people).

**Comment by adamjermyn** [comment]
99.872% of use cases are now covered.

**Comment by DouglasBoubert** [comment]
My friend, we are only just getting started.

`from past import british_empire`

**Comment by adamjermyn** [comment]
And from future?

**Comment by DouglasBoubert** [comment]
`from future import oceania.airstrip_one`
